#!/bin/bash


# docker stop Abathur;
# docker rm Abathur;



docker run  -p 3000:3000 -it  --name  Abathur  -d \
 -v ~/Abathur:/root -w /root python:2-slim \




docker exec  Abathur  pip install flask;

docker exec -d Abathur  python app.py;
